### ISSUE TITLE
关于迁移到新版本遇到的一些问题

### ISSUE THREAD

**Issue by wherewhere** [SinoAHpx/ModuleLauncher.Re#25]
首先，请不要随意更改命名空间或删除方法，更新到4.x之后命名空间完全改变了，这使得项目无法顺利的从3.x迁移到4.x，希望之后不要轻易更改命名空间，对于过时的方法请保留并标注已过时，然后在几个版本后再删除
同时请不要将.net目标版本设置的过于高，这将导致几乎没有项目可以引用这个库，建议使用TargetFrameworks，同时支持.netfx，.netstandard和.netcoreapp（.netstandard是一个标准，不存在过时或不过时，建议.netstandard设置为2.0

**Comment by SinoAHpx** [comment]
如你所见，4.x之后的版本是完全重写的，因为在我看来在3.x及其之前的所有版本都是糟糕的残次品，已经不值得做向下兼容的考量。
另外就是关于 TargetFramework 的问题，因为 .NET Standard 2.0 比起 .NET 6.0 缺少了许多 API，所以没有使用它而是直接用了 .NET 6.0。这点如果有人需要，可能会进行支持。

**Comment by wherewhere** [comment]
一般来说.netstandard已经和正常.net一模一样了，缺少什么就补什么，而且不止.netstandard，.netframework也要有，一般来说都是一个fx一个standard一个coreapp，这样既有原生和也有跨平台的了

**Comment by wherewhere** [comment]
还有就是如果是重写了的项目的话最好是换再个ID，然后标记旧的nuget为已过时，nuget一般都是标记的>=，如果不向下兼容会导致引用了不同版本的轮子互相乱套

**Comment by SinoAHpx** [comment]
收到收到收到，但可预计的几个月里都会很忙，几乎没有任何时间维护这个项目。
如果你愿意的话，我可以邀请你当 collaborator（

**Comment by wherewhere** [comment]
请问这里的项目是本体吗？我尝试提交个pr

**Comment by SinoAHpx** [comment]
其实你还可以自己开个一个自用 fork 啦，因为这个库是 MIT 协议

**Comment by wherewhere** [comment]
(实际上我早就弃坑了，不搓启动器了，只是看到只支持.net6有点难受就想改改
(隔壁也是只支持.net6，.net6才出现多久，怎么一个个都只支持.net6。。。

**Comment by wherewhere** [comment]
坏诶，我改不了，你引用了一个你写的只支持.net6的包。。。
