### ISSUE TITLE
调用微软登录API时发生错误

### ISSUE THREAD

**Issue by akchiji888** [SinoAHpx/ModuleLauncher.Re#26]
我在调用AuthenticateAsync()时发生以下异常：Flurl.Http.FlurlHttpException:“Call failed with status code 400 (Bad Request): POST https://login.live.com/oauth20_token.srf”
代码如下：
```
var authenticator = new MicrosoftAuthenticator();
var result = await authenticator.AuthenticateAsync();
```

**Comment by SinoAHpx** [comment]
因为你没有传入必要的属性 'code'
你得先在网页浏览器/Webview 里面完成登录操作，然后获得重定向后的url，再提取code。
详情请参阅文档。

**Comment by akchiji888** [comment]
哦哦哦，好的好的，谢谢谢谢
