### ISSUE TITLE
增加一个方法

### ISSUE THREAD

**Issue by akchiji888** [SinoAHpx/ModuleLauncher.Re#27]
增加一个方法，使得用户可以在指定的.minecraft路径下寻找存在的Minecraft Version

（就跟隔壁projbobcat的GetAllGames()差不多）

**Comment by SinoAHpx** [comment]
因为很忙，可能要过很久才会更新

**Comment by akchiji888** [comment]
没事了，找到临时的解决方案了（但就是把projbobcat也塞程序里了）（issue就先不关了，等这玩意儿增加了再关）

**Comment by SinoAHpx** [comment]
昨天看错了，实际上这个需求完全可以根据现有的条件来实现，而且很简单。
```
var resolver = new MinecraftResolver(@"C:\Users\ahpx\AppData\Roaming\.minecraft");
var existingMcs = resolver.GetMinecrafts().Where(m => m.Tree.Jar.Exists);
```
只需要像这样获取到一个 `MinecraftEntry` 序列，然后就可以调用 `Where` 方法筛选出存在的 Minecraft 版本
