### ISSUE TITLE
文档打不开

### ISSUE THREAD

**Issue by Peter1224** [SinoAHpx/ModuleLauncher.Re#7]
https://ahpxchina.github.io/ModuleLauncher.Re.Document 打不开

**Comment by SinoAHpx** [comment]
sinoahpx.github.io

**Comment by XiaoYejunAWA** [comment]
hmm貌似博客里也没有诶

**Comment by SinoAHpx** [comment]
https://blog.ahpxchina.cn/ModuleLauncher.Re.Document/

**Comment by XiaoYejunAWA** [comment]
好的，看到了，谢谢

**Comment by SinoAHpx** [comment]
btw这个库已经有几个月没更新了，虽然未来确实有更新计划，也打算继续维护。
